[servers]
        [servers.main]
                # IP of the server
                ip = "127.0.0.1"
                # The username to login to
                username = "root"
                # An optional description of the server
                description = "Main server"
                # The password for the server, optional
                password = ""
                # The path to the private key file to authenticate with, optional
                key_file = ""
